"""报告生成器 — 支持 JSON / HTML / PDF 格式导出"""

import json
from datetime import datetime


def generate_json_report(vulnerabilities: list[dict], task_info: dict) -> str:
    """生成 JSON 格式报告"""
    report = {
        "title": "Web 漏洞扫描报告",
        "generated_at": datetime.utcnow().isoformat(),
        "scanner": "VulnScanner v1.0",
        "task": task_info,
        "summary": {
            "total_vulnerabilities": len(vulnerabilities),
            "by_severity": _count_by_severity(vulnerabilities),
            "by_type": _count_by_type(vulnerabilities),
        },
        "vulnerabilities": vulnerabilities,
    }
    return json.dumps(report, ensure_ascii=False, indent=2)


def generate_html_report(vulnerabilities: list[dict], task_info: dict) -> str:
    """生成 HTML 格式报告"""
    severity_colors = {
        "critical": "#dc3545",
        "high": "#fd7e14",
        "medium": "#ffc107",
        "low": "#28a745",
        "info": "#17a2b8",
    }

    vuln_cards = ""
    for v in vulnerabilities:
        color = severity_colors.get(v.get("severity", "info"), "#6c757d")
        vuln_cards += f"""
        <div style="border:1px solid {color};margin:10px 0;padding:15px;border-left:5px solid {color}">
            <h3>[{v.get('severity', '').upper()}] {v.get('vuln_type', '')} — {v.get('endpoint', '')}</h3>
            <p><strong>参数:</strong> {v.get('parameter', '')} | <strong>方法:</strong> {v.get('method', '')}</p>
            <p><strong>Payload:</strong> <code>{v.get('payload', '')}</code></p>
            <p><strong>描述:</strong> {v.get('description', '')}</p>
            <details>
                <summary>PoC</summary>
                <pre><code>{v.get('poc', '')}</code></pre>
            </details>
            <details>
                <summary>修复建议</summary>
                <p>{v.get('remediation', '')}</p>
            </details>
        </div>"""

    severity_summary = ""
    for sev, count in _count_by_severity(vulnerabilities).items():
        severity_summary += f'<span style="background:{severity_colors.get(sev)};color:white;padding:3px 8px;margin:0 5px;border-radius:3px">{sev}: {count}</span>'

    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>VulnScanner 扫描报告</title>
    <style>
        body {{ font-family: -apple-system, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
        .header {{ background: linear-gradient(135deg, #1a1a2e, #16213e); color: white; padding: 30px; border-radius: 8px; }}
        .summary {{ display: flex; gap: 20px; margin: 20px 0; }}
        .stat-box {{ background: white; border-radius: 8px; padding: 20px; flex: 1; text-align: center; box-shadow: 0 2px 4px rgba(0,0,0,.1); }}
        .stat-box h2 {{ margin: 0; color: #1a1a2e; }}
        .stat-box p {{ color: #666; }}
        code {{ background: #f0f0f0; padding: 2px 6px; border-radius: 3px; }}
        pre {{ background: #282c34; color: #abb2bf; padding: 15px; border-radius: 6px; overflow-x: auto; }}
        details {{ margin-top: 10px; }}
        details summary {{ cursor: pointer; color: #2563eb; }}
        .footer {{ text-align: center; color: #999; margin-top: 40px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ Web 漏洞扫描报告</h1>
        <p>扫描目标: {task_info.get('target_url', '')}</p>
        <p>扫描时间: {task_info.get('started_at', '')} | 扫描深度: {task_info.get('scan_depth', '')}</p>
    </div>

    <div class="summary">
        <div class="stat-box">
            <h2>{len(vulnerabilities)}</h2>
            <p>发现漏洞</p>
        </div>
        <div class="stat-box">
            <div>{severity_summary}</div>
            <p>严重等级分布</p>
        </div>
    </div>

    <h2>漏洞详情</h2>
    {vuln_cards}

    <div class="footer">
        <p>Generated by VulnScanner v1.0 — {datetime.utcnow().isoformat()}</p>
    </div>
</body>
</html>"""


def _count_by_severity(vulnerabilities: list[dict]) -> dict:
    """按严重等级统计"""
    counts = {}
    for v in vulnerabilities:
        sev = v.get("severity", "unknown")
        counts[sev] = counts.get(sev, 0) + 1
    return dict(sorted(counts.items()))


def _count_by_type(vulnerabilities: list[dict]) -> dict:
    """按漏洞类型统计"""
    counts = {}
    for v in vulnerabilities:
        vt = v.get("type", v.get("vuln_type", "unknown"))
        counts[vt] = counts.get(vt, 0) + 1
    return counts

def generate_pdf_report(vulnerabilities: list[dict], task_info: dict) -> bytes:
    """生成 PDF 格式报告"""
    try:
        from weasyprint import HTML
        html_content = _build_report_html(vulnerabilities, task_info)
        return HTML(string=html_content).write_pdf()
    except ImportError:
        raise RuntimeError("weasyprint 未安装，无法生成 PDF")

def _build_report_html(vulnerabilities, task_info):
    severity_colors = {"critical": "#dc3545", "high": "#fd7e14", "medium": "#ffc107", "low": "#28a745", "info": "#17a2b8"}
    vuln_rows = ""
    for v in vulnerabilities:
        c = severity_colors.get(v.get("severity", "info"), "#6c757d")
        vuln_rows += f"<tr><td style=\\"color:{c};font-weight:bold\\">{v.get(\"severity\",\"\").upper()}</td><td>{v.get(\"vuln_type\",\"\")}</td><td style=\\"font-family:monospace;font-size:12px\\">{v.get(\"endpoint\",\"\")}</td><td>{v.get(\"parameter\",\"\")}</td></tr>"
    from datetime import datetime
    return f"""<!DOCTYPE html><html><head><meta charset=\\"utf-8\\"><style>
        body{{font-family:sans-serif;padding:40px}}h1{{color:#1a1a2e}}h2{{color:#e94560}}
        table{{width:100%;border-collapse:collapse;margin:20px 0}}
        th{{background:#1a1a2e;color:white;padding:10px;text-align:left}}
        td{{padding:8px;border-bottom:1px solid #ddd}}
        .summary{{display:flex;gap:20px;margin:20px 0}}
        .stat{{background:#f5f5f5;padding:15px;border-radius:8px;text-align:center;flex:1}}
        .stat h3{{margin:0;font-size:28px;color:#1a1a2e}}pre{{background:#282c34;color:#abb2bf;padding:15px;border-radius:6px;font-size:12px}}
    </style></head><body>
        <h1>Web漏洞扫描报告</h1>
        <p>目标: {task_info.get("target_url","")} | 时间: {task_info.get("started_at","")} | 深度: {task_info.get("scan_depth","")}</p>
        <div class=\\"summary\\"><div class=\\"stat\\"><h3>{len(vulnerabilities)}</h3><p>发现漏洞</p></div></div>
        <h2>漏洞清单</h2>
        <table><tr><th>严重度</th><th>类型</th><th>端点</th><th>参数</th></tr>{vuln_rows}</table>
        <h2>漏洞详情</h2>
        {"".join(f"<h3 style=\\"color:{severity_colors.get(v.get(\"severity\",\"\"),\"#333\")}\\">{v.get(\"severity\",\"\").upper()} — {v.get(\"vuln_type\",\"\")} — {v.get(\"parameter\",\"\")}</h3><p>{v.get(\"description\",\"\")}</p><pre>PoC:{v.get(\"poc\",\"\")}</pre><p><strong>修复:</strong> {v.get(\"remediation\",\"\")}</p>" for v in vulnerabilities)}
        <p style=\\"text-align:center;color:#999;margin-top:40px\\">Generated by VulnScanner v2.0 — {datetime.utcnow().isoformat()}</p>
    </body></html>"""

