"""报告生成器 — 支持 JSON / HTML / PDF 格式导出"""

import json
from datetime import datetime


def generate_json_report(vulnerabilities: list[dict], task_info: dict) -> str:
    """生成 JSON 格式报告"""
    report = {
        "title": "Web 漏洞扫描报告",
        "generated_at": datetime.utcnow().isoformat(),
        "scanner": "VulnScanner v1.0",
        "task": task_info,
        "summary": {
            "total_vulnerabilities": len(vulnerabilities),
            "by_severity": _count_by_severity(vulnerabilities),
            "by_type": _count_by_type(vulnerabilities),
        },
        "vulnerabilities": vulnerabilities,
    }
    return json.dumps(report, ensure_ascii=False, indent=2)


def generate_html_report(vulnerabilities: list[dict], task_info: dict) -> str:
    """生成 HTML 格式报告"""
    severity_colors = {
        "critical": "#dc3545",
        "high": "#fd7e14",
        "medium": "#ffc107",
        "low": "#28a745",
        "info": "#17a2b8",
    }

    vuln_cards = ""
    for v in vulnerabilities:
        color = severity_colors.get(v.get("severity", "info"), "#6c757d")
        vuln_cards += f"""
        <div style="border:1px solid {color};margin:10px 0;padding:15px;border-left:5px solid {color}">
            <h3>[{v.get('severity', '').upper()}] {v.get('vuln_type', '')} — {v.get('endpoint', '')}</h3>
            <p><strong>参数:</strong> {v.get('parameter', '')} | <strong>方法:</strong> {v.get('method', '')}</p>
            <p><strong>Payload:</strong> <code>{v.get('payload', '')}</code></p>
            <p><strong>描述:</strong> {v.get('description', '')}</p>
            <details>
                <summary>PoC</summary>
                <pre><code>{v.get('poc', '')}</code></pre>
            </details>
            <details>
                <summary>修复建议</summary>
                <p>{v.get('remediation', '')}</p>
            </details>
        </div>"""

    severity_summary = ""
    for sev, count in _count_by_severity(vulnerabilities).items():
        severity_summary += f'<span style="background:{severity_colors.get(sev)};color:white;padding:3px 8px;margin:0 5px;border-radius:3px">{sev}: {count}</span>'

    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>VulnScanner 扫描报告</title>
    <style>
        body {{ font-family: -apple-system, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
        .header {{ background: linear-gradient(135deg, #1a1a2e, #16213e); color: white; padding: 30px; border-radius: 8px; }}
        .summary {{ display: flex; gap: 20px; margin: 20px 0; }}
        .stat-box {{ background: white; border-radius: 8px; padding: 20px; flex: 1; text-align: center; box-shadow: 0 2px 4px rgba(0,0,0,.1); }}
        .stat-box h2 {{ margin: 0; color: #1a1a2e; }}
        .stat-box p {{ color: #666; }}
        code {{ background: #f0f0f0; padding: 2px 6px; border-radius: 3px; }}
        pre {{ background: #282c34; color: #abb2bf; padding: 15px; border-radius: 6px; overflow-x: auto; }}
        details {{ margin-top: 10px; }}
        details summary {{ cursor: pointer; color: #2563eb; }}
        .footer {{ text-align: center; color: #999; margin-top: 40px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ Web 漏洞扫描报告</h1>
        <p>扫描目标: {task_info.get('target_url', '')}</p>
        <p>扫描时间: {task_info.get('started_at', '')} | 扫描深度: {task_info.get('scan_depth', '')}</p>
    </div>

    <div class="summary">
        <div class="stat-box">
            <h2>{len(vulnerabilities)}</h2>
            <p>发现漏洞</p>
        </div>
        <div class="stat-box">
            <div>{severity_summary}</div>
            <p>严重等级分布</p>
        </div>
    </div>

    <h2>漏洞详情</h2>
    {vuln_cards}

    <div class="footer">
        <p>Generated by VulnScanner v1.0 — {datetime.utcnow().isoformat()}</p>
    </div>
</body>
</html>"""


def _count_by_severity(vulnerabilities: list[dict]) -> dict:
    """按严重等级统计"""
    counts = {}
    for v in vulnerabilities:
        sev = v.get("severity", "unknown")
        counts[sev] = counts.get(sev, 0) + 1
    return dict(sorted(counts.items()))


def _count_by_type(vulnerabilities: list[dict]) -> dict:
    """按漏洞类型统计"""
    counts = {}
    for v in vulnerabilities:
        vt = v.get("type", v.get("vuln_type", "unknown"))
        counts[vt] = counts.get(vt, 0) + 1
    return counts
