<template>
  <div class="report-view" v-loading="loading">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;">
      <h2>📄 扫描报告</h2>
      <div>
        <el-button @click="exportJSON">📥 导出 JSON</el-button>
        <el-button type="primary" @click="exportHTML">📥 导出 HTML</el-button>
        <el-button @click="$router.push(`/tasks/${taskId}`)">← 返回任务</el-button>
      </div>
    </div>

    <!-- 报告预览 -->
    <div v-if="reportHtml" class="report-preview" v-html="reportHtml"></div>

    <el-empty v-else-if="!loading" description="无法生成报告" />
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { taskApi, resultApi } from '../api/tasks'
import { ElMessage } from 'element-plus'

const route = useRoute()
const taskId = route.query.task_id || ''
const loading = ref(false)
const reportHtml = ref('')
const reportData = ref(null)

function severityColors(sev) {
  const m = { critical: '#dc3545', high: '#fd7e14', medium: '#ffc107', low: '#28a745', info: '#17a2b8' }
  return m[sev] || '#6c757d'
}

async function loadReport() {
  if (!taskId) return
  loading.value = true
  try {
    const [taskRes, resultsRes] = await Promise.all([
      taskApi.get(taskId),
      resultApi.listByTask(taskId),
    ])

    const task = taskRes.data.task
    const vulns = resultsRes.data.vulnerabilities || []
    reportData.value = { task, vulns }

    // 构建 HTML 报告预览
    const sevSummary = {}
    vulns.forEach(v => {
      sevSummary[v.severity] = (sevSummary[v.severity] || 0) + 1
    })
    const sevTags = Object.entries(sevSummary)
      .map(([s, c]) => `<span style="background:${severityColors(s)};color:white;padding:3px 8px;margin:0 3px;border-radius:3px;font-size:12px;">${s}: ${c}</span>`)
      .join('')

    const vulnCards = vulns.map(v => `
      <div style="border-left:4px solid ${severityColors(v.severity)};background:white;padding:15px;margin:10px 0;border-radius:4px;box-shadow:0 1px 3px rgba(0,0,0,.1);">
        <h4 style="margin:0 0 10px;color:#1a1a2e;">
          <span style="background:${severityColors(v.severity)};color:white;padding:2px 8px;border-radius:3px;font-size:12px;margin-right:8px;">${v.severity.toUpperCase()}</span>
          ${v.vuln_type === 'sqli' ? 'SQL注入' : v.vuln_type === 'xss' ? 'XSS' : '文件上传'}
        </h4>
        <p><strong>端点:</strong> <code>${v.endpoint}</code></p>
        <p><strong>参数:</strong> ${v.parameter} (${v.method})</p>
        <p><strong>Payload:</strong> <code>${v.payload?.substring(0, 200) || ''}</code></p>
        <p><strong>描述:</strong> ${v.description || ''}</p>
        <details>
          <summary style="cursor:pointer;color:#409eff;">PoC & 修复建议</summary>
          <pre style="background:#282c34;color:#abb2bf;padding:10px;border-radius:4px;font-size:12px;"><code>${v.poc || '无'}</code></pre>
          <p style="background:#f0f9eb;padding:10px;border-radius:4px;"><strong>修复:</strong> ${v.remediation || ''}</p>
        </details>
      </div>
    `).join('')

    reportHtml.value = `
      <div style="font-family:-apple-system,sans-serif;max-width:900px;margin:0 auto;padding:20px;">
        <div style="background:linear-gradient(135deg,#1a1a2e,#16213e);color:white;padding:30px;border-radius:10px;margin-bottom:20px;">
          <h1 style="margin:0;">🛡️ Web 漏洞扫描报告</h1>
          <p style="margin:10px 0 0;">目标: ${task.target_url}</p>
          <p>扫描时间: ${task.started_at || task.created_at} | 深度: ${task.scan_depth} 层</p>
        </div>
        <div style="display:flex;gap:15px;margin-bottom:20px;">
          <div style="flex:1;background:white;padding:20px;border-radius:8px;text-align:center;box-shadow:0 1px 3px rgba(0,0,0,.1);">
            <h2 style="color:#e94560;font-size:32px;margin:0;">${vulns.length}</h2>
            <p style="color:#999;">发现漏洞</p>
          </div>
          <div style="flex:2;background:white;padding:20px;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,.1);">
            <p style="margin:5px 0;">${sevTags}</p>
          </div>
        </div>
        <h2>漏洞详情</h2>
        ${vulnCards}
        <p style="text-align:center;color:#999;margin-top:40px;">Generated by VulnScanner v1.0</p>
      </div>
    `
  } catch (e) {
    ElMessage.error('加载报告失败')
  }
  loading.value = false
}

function exportJSON() {
  if (!reportData.value) return
  const data = JSON.stringify(reportData.value, null, 2)
  downloadFile(`vuln_report_${taskId}.json`, data, 'application/json')
}

function exportHTML() {
  if (!reportHtml.value) return
  downloadFile(`vuln_report_${taskId}.html`, reportHtml.value, 'text/html')
}

function downloadFile(filename, content, type) {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
  ElMessage.success(`报告已导出: ${filename}`)
}

onMounted(loadReport)
</script>

<style scoped>
.report-view h2 { color: #1a1a2e; }
.report-preview { background: #f0f2f5; border-radius: 8px; padding: 20px; }
</style>
